[package]
name = "askua-starknet"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.9", features = ["json"] }
rig-core.workspace = true
serde = { workspace = true }
serde_json = { workspace = true }
starknet = "0.12.0"
thiserror = { workspace = true }
